In [ ]:
import requests

In [ ]:
url = "https://www.worldometers.info/gdp/nepal-gdp/"
html = requests.get(url).content

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(html, "html.parser")

In [ ]:
table = soup.find_all("table")[1]
title = table.find_all("th")
table_title = [item.text for item in title]
table_title

['Year',
 'GDP Nominal (Current USD) ',
 'GDP Real  (Inflation adj.) ',
 'GDP change',
 'GDP per capita',
 'Pop. change',
 'Population']

In [ ]:
import pandas as pd
df = pd.DataFrame(columns=table_title)
df

Empty DataFrame
Columns: [Year, GDP Nominal (Current USD) , GDP Real  (Inflation adj.) , GDP change, GDP per capita, Pop. change, Population]
Index: []

In [ ]:
all_table_row = table.find_all("tr")
for row in all_table_row[1:]:
    row_data = row.find_all("td")
    data = [item.text for item in row_data]
    length = len(df)
    df.loc[length] = data

In [ ]:
df

,Year,GDP Nominal (Current USD),GDP Real (Inflation adj.),GDP change,GDP per capita,Pop. change,Population
0,2022,"$40,828,247,302","$33,084,084,559",5.61%,"$1,083",1.71 %,"30,547,580"
1,2021,"$36,924,841,430","$31,325,711,843",4.84%,"$1,043",2.34 %,"30,034,989"
2,2020,"$33,433,659,223","$29,880,069,382",-2.37%,"$1,018",1.79 %,"29,348,627"
3,2019,"$34,186,180,695","$30,605,298,856",6.66%,"$1,061",1.14 %,"28,832,496"
4,2018,"$33,111,525,183","$28,695,053,256",7.62%,"$1,007",1.15 %,"28,506,712"
5,2017,"$28,971,588,881","$26,662,720,424",8.98%,$946,1.16 %,"28,183,426"
6,2016,"$24,524,109,485","$24,466,311,310",0.43%,$878,0.91 %,"27,861,186"
7,2015,"$24,360,801,338","$24,360,801,338",3.98%,$882,0.54 %,"27,610,325"
8,2014,"$22,731,612,827","$23,429,242,187",6.01%,$853,0.29 %,"27,462,106"
9,2013,"$22,162,205,046","$22,100,664,531",3.53%,$807,0.19 %,"27,381,555"
10,2012,"$21,703,100,747","$21,348,110,921",4.67%,$781,0.24 %,"27,330,694"
11,2011,"$21,573,872,274","$20,395,607,123",3.42%,$748,0.39 %,"27,266,399"
12,2010,"$16,002,656,434","$19,720,799,103",4.82%,$726,0.50 %,"27,161,567"
13,2009,"$12,854,985,464","$18,814,609,496",4.53%,$696,0.54 %,"27,026,941"
14,2008,"$12,545,438,605","$17,998,713,637",6.10%,$670,0.63 %,"26,881,544"
15,2007,"$10,325,618,017","$16,963,173,130",3.41%,$635,0.73 %,"26,713,655"
16,2006,"$9,043,715,356","$16,403,555,931",3.36%,$619,0.89 %,"26,518,971"
17,2005,"$8,130,258,415","$15,869,604,861",3.48%,$604,1.08 %,"26,285,110"
18,2004,"$7,273,938,315","$15,336,036,389",4.68%,$590,1.25 %,"26,003,965"
19,2003,"$6,330,473,097","$14,650,033,447",3.95%,$570,1.38 %,"25,682,908"
20,2002,"$6,050,875,807","$14,094,019,072",0.12%,$556,1.51 %,"25,332,178"
21,2001,"$6,007,055,042","$14,077,106,389",4.80%,$564,1.61 %,"24,956,071"
22,2000,"$5,494,252,208","$13,432,367,249",6.20%,$547,1.72 %,"24,559,500"
23,1999,"$5,033,642,384","$12,648,180,086",4.41%,$524,1.86 %,"24,143,157"
24,1998,"$4,856,255,044","$12,113,656,132",3.02%,$511,1.95 %,"23,703,328"
25,1997,"$4,918,691,917","$11,758,960,097",5.05%,$506,2.04 %,"23,249,417"
26,1996,"$4,521,580,381","$11,193,827,136",5.33%,$491,2.14 %,"22,783,969"
27,1995,"$4,401,104,418","$10,627,560,511",3.47%,$476,2.34 %,"22,305,571"
28,1994,"$4,066,775,510","$10,271,305,231",8.22%,$471,2.48 %,"21,794,751"
29,1993,"$3,660,041,667","$9,491,484,600",3.85%,$446,2.73 %,"21,267,359"

In [ ]:
data_csv = df.to_csv("data.csv", index=False)

In [ ]:
data_to_db = df.to_records(index=False)

In [24]:
import sqlite3

In [25]:
con = sqlite3.connect("data.db")
cur = con.cursor()

In [26]:
query = """create table gdp(year varchar[20], nominal varchar[20], real varchar[20], change varchar[20], percapita varchar[20], popchange varchar[20], population varchar[20])"""

In [27]:
try:
    cur.execute(query)
except Exception as e:
    print(e)

In [28]:
query = """insert into gdp(year, nominal, real, change, percapita, popchange, population)
            values(?, ?, ?, ?, ?, ?, ?)"""
cur.executemany(query, data_to_db)

In [33]:
cur.execute("select * from gdp").fetchall()

[('2022',
  '$40,828,247,302',
  '$33,084,084,559',
  '5.61%',
  '$1,083',
  '1.71 %',
  '30,547,580'),
 ('2021',
  '$36,924,841,430',
  '$31,325,711,843',
  '4.84%',
  '$1,043',
  '2.34 %',
  '30,034,989'),
 ('2020',
  '$33,433,659,223',
  '$29,880,069,382',
  '-2.37%',
  '$1,018',
  '1.79 %',
  '29,348,627'),
 ('2019',
  '$34,186,180,695',
  '$30,605,298,856',
  '6.66%',
  '$1,061',
  '1.14 %',
  '28,832,496'),
 ('2018',
  '$33,111,525,183',
  '$28,695,053,256',
  '7.62%',
  '$1,007',
  '1.15 %',
  '28,506,712'),
 ('2017',
  '$28,971,588,881',
  '$26,662,720,424',
  '8.98%',
  '$946',
  '1.16 %',
  '28,183,426'),
 ('2016',
  '$24,524,109,485',
  '$24,466,311,310',
  '0.43%',
  '$878',
  '0.91 %',
  '27,861,186'),
 ('2015',
  '$24,360,801,338',
  '$24,360,801,338',
  '3.98%',
  '$882',
  '0.54 %',
  '27,610,325'),
 ('2014',
  '$22,731,612,827',
  '$23,429,242,187',
  '6.01%',
  '$853',
  '0.29 %',
  '27,462,106'),
 ('2013',
  '$22,162,205,046',
  '$22,100,664,531',
  '3.53%',
  '$807',
  '0.19 %',
  '27,381,555'),
 ('2012',
  '$21,703,100,747',
  '$21,348,110,921',
  '4.67%',
  '$781',
  '0.24 %',
  '27,330,694'),
 ('2011',
  '$21,573,872,274',
  '$20,395,607,123',
  '3.42%',
  '$748',
  '0.39 %',
  '27,266,399'),
 ('2010',
  '$16,002,656,434',
  '$19,720,799,103',
  '4.82%',
  '$726',
  '0.50 %',
  '27,161,567'),
 ('2009',
  '$12,854,985,464',
  '$18,814,609,496',
  '4.53%',
  '$696',
  '0.54 %',
  '27,026,941'),
 ('2008',
  '$12,545,438,605',
  '$17,998,713,637',
  '6.10%',
  '$670',
  '0.63 %',
  '26,881,544'),
 ('2007',
  '$10,325,618,017',
  '$16,963,173,130',
  '3.41%',
  '$635',
  '0.73 %',
  '26,713,655'),
 ('2006',
  '$9,043,715,356',
  '$16,403,555,931',
  '3.36%',
  '$619',
  '0.89 %',
  '26,518,971'),
 ('2005',
  '$8,130,258,415',
  '$15,869,604,861',
  '3.48%',
  '$604',
  '1.08 %',
  '26,285,110'),
 ('2004',
  '$7,273,938,315',
  '$15,336,036,389',
  '4.68%',
  '$590',
  '1.25 %',
  '26,003,965'),
 ('2003',
  '$6,330,473,097',
  '$14,650,033,447',
  '3.95%',
  '$570',
  '1.38 %',
  '25,682,908'),
 ('2002',
  '$6,050,875,807',
  '$14,094,019,072',
  '0.12%',
  '$556',
  '1.51 %',
  '25,332,178'),
 ('2001',
  '$6,007,055,042',
  '$14,077,106,389',
  '4.80%',
  '$564',
  '1.61 %',
  '24,956,071'),
 ('2000',
  '$5,494,252,208',
  '$13,432,367,249',
  '6.20%',
  '$547',
  '1.72 %',
  '24,559,500'),
 ('1999',
  '$5,033,642,384',
  '$12,648,180,086',
  '4.41%',
  '$524',
  '1.86 %',
  '24,143,157'),
 ('1998',
  '$4,856,255,044',
  '$12,113,656,132',
  '3.02%',
  '$511',
  '1.95 %',
  '23,703,328'),
 ('1997',
  '$4,918,691,917',
  '$11,758,960,097',
  '5.05%',
  '$506',
  '2.04 %',
  '23,249,417'),
 ('1996',
  '$4,521,580,381',
  '$11,193,827,136',
  '5.33%',
  '$491',
  '2.14 %',
  '22,783,969'),
 ('1995',
  '$4,401,104,418',
  '$10,627,560,511',
  '3.47%',
  '$476',
  '2.34 %',
  '22,305,571'),
 ('1994',
  '$4,066,775,510',
  '$10,271,305,231',
  '8.22%',
  '$471',
  '2.48 %',
  '21,794,751'),
 ('1993',
  '$3,660,041,667',
  '$9,491,484,600',
  '3.85%',
  '$446',
  '2.73 %',
  '21,267,359')]

In [32]:
cur.execute("select population from gdp where year = '2000'").fetchall()

[('24,559,500',)]